name: flask_mod_struct_python_checker
on:
  push:
    branches: [ master ]
    paths:
      - 'app_server/**'
      - 'manage_commands/**'
      - 'manage.py'
  pull_request:
    branches: [ master ]
    paths:
      - 'app_server/**'
      - 'manage_commands/**'
      - 'manage.py'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check length of line in app_server modules
        id: long_line_checker_app_server
        run: |
          echo Checking length of line in app_server modules
          modules_ok=0
          modules=($(find app_server/ -type f -name '*.py' -exec echo '{}' \;))
          for mod in "${modules[@]}"; do line_length=$(wc -L < "${mod}"); [[ $line_length -gt 80 ]] && modules_ok=1; done
          [[ $modules_ok -eq 0 ]] && echo ::set-output name=status::success || echo ::set-output name=status::failure
      - name: Check length of line in manage_commands modules
        id: long_line_checker_manage_commands
        run: |
          echo Checking length of line in manage_commands modules
          modules_ok=0
          modules=($(find manage_commands/ -type f -name '*.py' -exec echo '{}' \;))
          for mod in "${modules[@]}"; do line_length=$(wc -L < "${mod}"); [[ $line_length -gt 80 ]] && modules_ok=1; done
          [[ $modules_ok -eq 0 ]] && echo ::set-output name=status::success || echo ::set-output name=status::failure
      - name: Check number of lines in app_server modules
        id: num_line_checker_app_server
        run: |
          echo Checking number of lines in app_server modules
          modules_ok=0
          modules=($(find app_server/ -type f -name '*.py' -exec echo '{}' \;))
          for mod in "${modules[@]}"; do line_numbers=$(wc -l < "${mod}"); [[ $line_numbers -gt 300 ]] && modules_ok=1; done
          [[ $modules_ok -eq 0 ]] && echo ::set-output name=status::success || echo ::set-output name=status::failure
      - name: Check number of lines in manage_commands modules
        id: num_line_checker_manage_commands
        run: |
          echo Checking number of lines in manage_commands modules
          modules_ok=0
          modules=($(find manage_commands/ -type f -name '*.py' -exec echo '{}' \;))
          for mod in "${modules[@]}"; do line_numbers=$(wc -l < "${mod}"); [[ $line_numbers -gt 300 ]] && modules_ok=1; done
          [[ $modules_ok -eq 0 ]] && echo ::set-output name=status::success || echo ::set-output name=status::failure
      - name: Check on failures
        if: steps.long_line_checker_app_server.outputs.status == 'failure' || steps.long_line_checker_manage_commands.outputs.status == 'failure' || steps.num_line_checker_app_server.outouts.status == 'failure' || steps.num_line_checker_manage_commands.outputs.status == 'failure'
        run: exit 1
